FROM node:11.6.0-alpine as builder
COPY package.json ./
RUN yarn install && mkdir /vehicle-monitor-ui && mv ./node_modules ./vehicle-monitor-ui
WORKDIR /vehicle-monitor-ui
COPY . .
RUN yarn run build --prod --build-optimizer

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /vehicle-monitor-ui/dist /usr/share/nginx/html
COPY --from=builder /vehicle-monitor-ui/entrypoint.sh /usr/share/nginx/
EXPOSE 80
RUN chmod +x /usr/share/nginx/entrypoint.sh
CMD ["/bin/sh", "/usr/share/nginx/entrypoint.sh"]
